repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: .gitignore
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: charts\/.+templates\/.+yaml
      - id: check-added-large-files
        args: [--maxkb=1500]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/google/yamlfmt
    rev: v0.9.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: shellcheck
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
